### ISSUE TITLE
make tests run without internet connection

### ISSUE THREAD

**Issue by fkooman** [clue/php-socket-raw#24]
I'm creating a RPM package for Fedora/CentOS, but the build system does not have access to the Internet, so the unit tests I run at build time fail. Is it possible to make the tests work without access to the Internet?

**Comment by clue** [comment]
Thanks for filing this ticket @fkooman!

I think it makes sense to add a flag/toggle to turn this feature on/off. What do you think about something like this:

```bash
$ TEST_INTERNET=0 phpunit
```
