### ISSUE TITLE
Skip IPv6 tests for Travis CI

### ISSUE THREAD

**Issue by clue** [clue/php-socket-raw#25]
> **IPv6 no longer present**
The major change that is coming with this migration is that local and external IPv6 networking will no longer be present. This has been present and while technically not considered to be a feature, it has been available. With the move to GCE this will no longer work, until such time as as GCE adds IPv6 support. We do understand this may cause a disruption for some use cases and while we have considered numerous ways to try to provide IPv6 in the cloud, none of the current available options are suitable for a large production deployment. We ask for your understanding and patience with the fact that is will no be supported for the near future.

https://blog.travis-ci.com/2015-11-27-moving-to-a-more-elastic-future

**Comment by clue** [comment]
Let's recap: Travis offers two build systems:

* Legacy Precise builds, do not support IPv6 anymore, but allow running as root (raw/ICMP sockets)
* Newer container-based builds, much faster, do support IPv6, but do not allow running as root (no raw/ICMP sockets)

This means either way we can no longer run our full test suite on Travis. We either have to skip IPv6 or raw/ICMP tests.

Personally, I'd vote for skipping raw/ICMP tests instead of IPv6, as this feature is more likely going to used by consumers of this library.

**Comment by ascii-soup** [comment]
I wonder if there's a way of determining which type of build is being used? I'm afraid I know very little about Travis, but I can take a look at the other environment variables they provide to each script?

On balance, you're probably right, but if we could support both by selectively disabling the appropriate tests (with an appropriate skipped message) then that would probably be best.

**Comment by clue** [comment]
The raw/ICMP tests will already be skipped if the test suite can not create the socket due to permission problems (see https://github.com/clue/php-socket-raw/blob/4787a7d9669c114f343bfbccd9c03a417dd375b3/tests/FactoryTest.php#L180 and following).

The README also describes this behavior: https://github.com/clue/php-socket-raw#tests
 
This means we *could* change the Travis script to just run `phpunit` without `sudo` and we're ready to go.

**Comment by ascii-soup** [comment]
Ah yes, sorry it's been a while. 

So, just for my sake since I don't know much about Travis, are you suggesting that the Travis builds for php-socket-raw would only be run in the new container-based environments?

**Comment by clue** [comment]
> So, just for my sake since I don't know much about Travis, are you suggesting that the Travis builds for php-socket-raw would only be run in the new container-based environments?

Yeah, I suppose this would be a fair trade-off given the above evaluation. See PR #28.

**Comment by ascii-soup** [comment]
Works for me.
