### ISSUE TITLE
Multiple clients not connecting

### ISSUE THREAD

**Issue by kadnan** [clue/php-socket-raw#31]
So I am creating server and connecting multiple clients 

**Server.PHP**

```
<?php
include_once 'vendor/autoload.php';
$factory = new \Socket\Raw\Factory();
$socket = $factory->createServer('localhost:9999');
$socket->listen(10);
echo "Waiting for incoming connections... \n";

while(1) {
    $client = $socket->accept();
    $client_info = $client->getPeerName();
    if($client_info != null) {
        print 'Connect Client :-'.$client_info."\n";     
    }
    $data = $client->read(1024000);
    print $data."\n";
    $client->write('Agent said: '.$data);
}
```

**Client**
```
<?php
include_once 'vendor/autoload.php';
$factory = new \Socket\Raw\Factory();

$socket = $factory->createClient('localhost:9999');
echo 'Connected to ' . $socket->getPeerName() . PHP_EOL;

$index = 0;


// receive and dump HTTP response
//var_dump($socket->read(8192));
while(1) {
$socket->write("Client is here \n");
}
```

When I execute the code it just connects one client and in Server window it shows entry of one client only as
`Connect Client :-127.0.0.1:63031`

2nd , only sending data it throws error:

```
Fatal error: Uncaught exception 'Socket\Raw\Exception' with message 'Socket operation failed: Broken pipe (SOCKET_EPIPE)' in /abc/Server/vendor/clue/socket-raw/src/Exception.php:55
```

**Comment by clue** [comment]
Note that all socket functions are blocking by default.

You may use `$socket->setBlocking(false)` to enable non-blocking mode. This means that each of the above methods will no longer block. This will allow you to asynchronously check multiple sockets via `socket_select()` (and family).

If you really want to do this, I highly recommend taking a look at https://github.com/reactphp/socket and optionally the binding to this lib https://github.com/clue/php-socket-react

I hope this helps :+1:

**Comment by kadnan** [comment]
@clue thanks for reply. Look I already have written script by using php old socket functions and it works fine. What I want to convert into OOP way. If your library is simply a wrapper then it should work and accept every connection?

**Comment by clue** [comment]
> @clue Note that all socket functions are blocking by default.
> @kadnan Look I already have written script by using php old socket functions and it works fine.

Yes, this library is merely a very small wrapper around the underlying socket functions. Note that this also means the above applies to the underlying socket functions just as well. In other words, you have to use select/poll/etc. in order to avoid blocking when working with multiple sockets.

If you're only checking a single socket, you can use something similar to this:

```php
// wait for socket to become readable (this is blocking)
if ($socket->selectRead()) {
    // read from socket
    // this is non-blocking, because it's guaranteed to be readable right away
    $data = $socket->read(8192);
}
```

If you're checking multiple sockets, you may have to use `socket_select()` manually. If we happen to come up with a good abstraction for this, I'd love to get this in here :+1:
