### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by sockmonkeyws** [clue/php-socket-raw#32]
Name can easily be confused with raw sockets which are available in PHP on OSs that allow such as Linux. [Raw socket on Wikipedia](https://en.m.wikipedia.org/wiki/Raw_socket)

**Comment by clue** [comment]
Thanks for opening this interesting issue :-)

I understand where you're coming from and agree that the name may in fact not be ideal.

Unfortunately, changing the Composer package name is not exactly an easy task, so I see little chance we're going to able to change this any time soon.

In the meantime, let's just consider "raw sockets" as "bare sockets and nothing else" :-)

I hope this helps :+1:
