### ISSUE TITLE
Factory has a number of undefined variables

### ISSUE THREAD

**Issue by halfer** [clue/php-socket-raw#34]
My IDE reveals the `Factory` class has two cases where an undefined variable is used, `$scheme`. I think this is used for write-back, but nevertheless it will raise a notice unnecessarily. This can be fixed by setting the var to something prior to using it:

    $scheme = null; // Prevents 'Undefined variable' notice
    $socket = $this->createFromString($address, $scheme);

I can send a PR if that is helpful.

**Comment by halfer** [comment]
Hi, is anyone maintaining this project? Thanks :smile_cat:

**Comment by clue** [comment]
Unless I'm missing something obvious, the variables are passed by reference and as such should not yield an "undefined variable notice".

While I don't see an issue here, I'm happy to accept PRs to discuss this further :+1:

**Comment by halfer** [comment]
You are right, apologies. I get warnings in my IDE (NetBeans) but if there's no run-time impact, there's no value in changing this.
