### ISSUE TITLE
Warning: Use of undefined constant AF_INET

### ISSUE THREAD

**Issue by fieg** [clue/php-socket-raw#35]
Just wanted to let you know about this warning I'm getting on PHP 7.2.1:

> Warning: Use of undefined constant AF_INET - assumed 'AF_INET' (this will throw an Error in a future version of PHP)
>
> Factory->createTcp4()
> in vendor/clue/socket-raw/src/Factory.php (line 247)

**Comment by fieg** [comment]
Nevermind, I forgot to install the sockets extension. Sorry, my bad.

**Comment by clue** [comment]
Was just about to suggest checking the extension, but happy to hear this is resolved 👍
