### ISSUE TITLE
How to write json data

### ISSUE THREAD

**Issue by codebeginer** [clue/php-socket-raw#36]
I want to send json data to socket server. Is it possible?
$notification = json_encode(["manoj"=>"thakur"]);
$socket->write($notification);

**Comment by clue** [comment]
Looks about right :+1: 

Depending on your particular protocol in use, you'll likely want to use some kind of message framing so the receiving side can detect when the incoming message is "complete". For example, if you only ever transport JSON messages, you may use a newline separator and effectively turn this into [NDJSON](http://ndjson.org).

I hope this helps :+1:
