### ISSUE TITLE
How to check if the connect is still alive?

### ISSUE THREAD

**Issue by danardf** [clue/php-socket-raw#40]
Hello.

I would like to know how to check if the connexion is still alive?
My code is used like a client. 
in PHP socket , i used stream_get_meta_data and check eof

**Comment by clue** [comment]
That's a very good question indeed!

The way the underlying socket API works means that you have to perform a socket operation to see if this is (still) successful. For example, you can use the `selectRead()` method to see if the connection is ready to read from and if a read call returns empty data, it means that the remote side closed the connection. See also https://github.com/clue/php-socket-raw/issues/20#issuecomment-146671813 for more details :+1: 

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
