### ISSUE TITLE
Need to understand the usage of library

### ISSUE THREAD

**Issue by sourabh21jain** [clue/php-socket-raw#46]
Hi
 
I have read the documentation of the library and have some query if the library is useful for my case or not. Can you please help me out - 
 
1. We are implementing a 2-way publisher-subscriber model using sockets.  We are planning to use this library one of our component who will publish/subscribe message to/from a socket service. Does this library support subscriber function? Which means listening for specific messages and execute an appropriate callback when the intended message is received.
2. Please let us know if there is any connection limitation(Timeouts, KeepAlive, Proxy issues, etc).
3. Any idea on the number of concurrent messages it can process simultaneously.
 
Thanks a ton! 
 
Sourabh Jain

**Comment by clue** [comment]
Hi @sourabh21jain, thanks for these good questions!

This library provides a simple abstraction over low level network sockets. This means that most applications will not interface with this directly, but will instead use some higher level implementation of top of this.

In your case, it sounds like you might be better off using a higher-level PubSub implementation like https://github.com/clue/reactphp-redis#pubsub instead?

To answer your questions:
1. Possible, but I would suggest using an event-driven approach instead: https://github.com/reactphp/socket#connectioninterface
2. No known limitations
3. No limitations inside this library. Depending on your operation system constraints, you're likely going to limited to 1024 file descriptors, but you can easily change this configuration.

I hope this helps :+1:
