### ISSUE TITLE
Failed to select socket for reading: Interrupted system call (SOCKET_EINTR) 

### ISSUE THREAD

**Issue by RyanBlundell** [clue/php-socket-raw#52]
Hi there, 

I am running php-socket-raw via nesk/puphpeteer. I am often running into the following error. Do you have any idea what is causing it? I can't seem to find anyone else with this issue but it is happening on two of my servers.

` PHP Fatal error:  Uncaught Socket\\Raw\\Exception: Failed to select socket for reading: Interrupted system call (SOCKET_EINTR) in /var/www/html/vendor/clue/socket-raw/src/Exception.php:59\nStack trace:\n#0 /var/www/html/vendor/clue/socket-raw/src/Exception.php(45): Socket\\Raw\\Exception::createFromCode(4, 'Failed to selec...')\n#1 /var/www/html/vendor/clue/socket-raw/src/Socket.php(307): Socket\\Raw\\Exception::createFromGlobalSocketOperation('Failed to selec...')\n#2 /var/www/html/vendor/nesk/rialto/src/ProcessSupervisor.php(408): Socket\\Raw\\Socket->selectRead(30)\n#3 /var/www/html/vendor/nesk/rialto/src/ProcessSupervisor.php(382): Nesk\\Rialto\\ProcessSupervisor->readNextProcessValue(true)\n#4 /var/www/html/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(84): Nesk\\Rialto\\ProcessSupervisor->executeInstruction(Object(Nesk\\Rialto\\Instruction))\n#5 /var/www/html/vendor/nesk/rialto/src/Traits/CommunicatesWithProcessSupervisor.php(100): Nesk\\Rialto\\AbstractEntryPoint->proxyAction('call', 'launch', Array)\n#6 /var/www/html/ind in /var/www/html/vendor/clue/socket-raw/src/Exception.php on line 59`

**Comment by clue** [comment]
@RyanBlundell Thanks for reporting.

It looks like your process is receiving a system signal (see `kill` etc.) while it is waiting for the socket to become readable. This library reports all errors/interruptions as an `Exception`, so this works as expected here.

It looks like you may want to report this downstream in nesk/realto or nesk/puphpeteer to ensure that the downstream component properly handles this error condition, for example force quit, retry or some other strategy depending on the use case. Please link back to this ticket for future reference.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Comment by RyanBlundell** [comment]
Nice one! Thanks so much for taking the time to give me such a detailed reply :)
