### ISSUE TITLE
socket timeout reply

### ISSUE THREAD

**Issue by eduardor2k** [clue/php-socket-raw#54]
Hi, i'm using the library with udp sockets, every works perfectly, but sometimes the server reply (ack) is lost and the script is left waiting for a reply.

I've set the timeout value, but it seems it's only set when creating the socket.

Anyone might know what i'm missing?

Thanks to all

**Comment by eduardor2k** [comment]
It seems i've found the solution.

        $socket = $this->socketFactory->createClient('udp://'.$ip.':'.$port, $this->getTimeout() );

        //missing from the library, add timeout to reply
        @socket_set_option($socket->getResource(), SOL_SOCKET, SO_RCVTIMEO, array('sec' => $this->getTimeout(), 'usec' => 0));

        $socket->write('mydata');
        $data = $socket->read(8192);
        $socket->shutdown();
        $socket->close();

I think we should add:

        @socket_set_option($socket->getResource(), SOL_SOCKET, SO_RCVTIMEO, array('sec' => $this->getTimeout(), 'usec' => 0));

when the client is created, this way the socket will take into account the timeout

- When creating the socket
- When waiting for a reply

**Comment by clue** [comment]
@eduardor2k Thanks for this question!

UDP is an unreliable protocol (it's in the initials), so lost packages are to be expected. Depending on your application or use-case you may want to retry after a timeout, ignore this condition or fail the connection.

UDP connections are also stateless in the sense that a connection setup is always instant (no data whatsoever is exchanged). This implies that setting a timeout for the connection phase has no effect here.

When receiving data, you can rely on the socket settings to configure a receive timeout. The `SO_RCVTIMEO` socket option can already be set like this:

```php
$socket->setOption(SOL_SOCKET, SO_RCVTIMEO, array('sec' => $this->getTimeout(), 'usec' => 0));
$data = $socket->read(8192); // reads or throws
```

As an alternative, you can also check the socket for readability with a timeout like this:

```php
// readable?
if ($socket->selectRead(1.5)) {
    // readable!
    $data = $socket->read(8192);
}
```

I hope this helps :+1:

**Comment by eduardor2k** [comment]
Thanks for your reply!
