### ISSUE TITLE
Read whois data

### ISSUE THREAD

**Issue by ostap-mykhaylyak** [clue/php-socket-raw#55]
Hi, I think I am missing something, but I cannot get a full response from the whois server:

```
<?php
require_once __DIR__ . '/vendor/autoload.php';

$factory = new \Socket\Raw\Factory();
try {
$socket = $factory->createClient('tcp://whois.nic.it:43');
echo 'Connected to ' . $socket->getPeerName() . PHP_EOL;

$data = $socket->write('ostap.it' . PHP_EOL);
var_dump($data);

var_dump($socket->read(128));

$socket->close();
} catch(Exception $var) {
  print $var->getMessage() . PHP_EOL;
}
```

the server response is empty:

```
Connected to 192.12.192.242:43
int(9)
string(0) ""
```

**Comment by clue** [comment]
@ostap-mykhaylyak Thanks for reporting, I don't see anything that's wrong with the code.

If you find this is a problem only with this library, please let me know and I'm happy to take a look again. If you're looking for individual support for a commercial project, please reach out via email and I'm sure this is something we can work out.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
