### ISSUE TITLE
socket_select accepts only integers

### ISSUE THREAD

**Issue by szepeviktor** [clue/php-socket-raw#56]
https://www.php.net/manual/en/function.fmod

```php
        $usec = $sec === null ? null : fmod($sec, 1) * 1e6;

        $ret = @socket_select($r, $w, $e, (int)$sec, (int)$usec);
```

What do you think about this?

**Comment by clue** [comment]
@szepeviktor Thanks for spotting :+1:

**Comment by szepeviktor** [comment]
You're welcome.
BTW it was @phpstan.

**Comment by clue** [comment]
https://phpstan.org/r/47de8c45-8636-46d7-8d08-3011f9bbc554 Looks like a minor bug in @phpstan by the way, both timeout arguments also support `null` values. Feel like filing an upstream PR? :+1:

**Comment by szepeviktor** [comment]
Yes, socket_select's signature need to be fixed in @phpstan.

https://github.com/phpstan/phpstan-src/blob/3e8ec5f0d4ecf3df531c9f674345508a8e1e51fa/resources/functionMap.php#L10346

**Comment by clue** [comment]
Go for it :+1:

**Comment by szepeviktor** [comment]
🏋️‍♂️ Done.
https://github.com/phpstan/phpstan-src/pull/385
